#!/usr/bin/env python3
"""
contact.py
──────────
Tags analog film scans with AI-generated metadata and writes XMP sidecar files
readable by Lightroom, darktable, Finder, and Spotlight.

Roll-level metadata (film stock, camera, lens, date, location) is provided via
a roll.yaml file in the scan folder. Per-frame content (description, tags,
category) is generated by a local Ollama vision model.

Usage:
    python3 contact.py --init ~/scans/tuscany/   # launch interactive roll setup
    python3 contact.py ~/scans/tuscany/           # tag all images in folder
    python3 contact.py ~/scans/tuscany/ --dry-run
    python3 contact.py ~/scans/tuscany/ --verbose
    python3 contact.py ~/scans/tuscany/ --force   # re-tag already tagged images
"""

import argparse
import subprocess
from pathlib import Path

from processor.roll import IMAGE_EXTS, load_roll_yaml, build_folder_name, run_roll_setup
from processor.tagger import analyze_image, write_roll_summary, ollama_ready, wait_for_ollama
from processor.sidecar import write_xmp, _read_xmp_meta
from processor.html import write_roll_html


# ── Main pipeline ─────────────────────────────────────────────────────────────


def process_folder(folder: Path, args, vision_model: str, text_model: str) -> None:
    """Tag all images in a single folder, write summary + HTML, optionally rename."""
    roll = load_roll_yaml(folder)
    if roll:
        print("Roll metadata:")
        for k, v in roll.items():
            if v:
                print(f"  {k}: {v}")
        print()
    else:
        print("No roll.yaml found — proceeding with content analysis only.\n")

    all_images = sorted(
        f for f in folder.iterdir()
        if f.is_file() and f.suffix.lower() in IMAGE_EXTS
    )

    if not args.force:
        images = [f for f in all_images if not f.with_suffix(".xmp").exists()]
        skipped = len(all_images) - len(images)
        if skipped:
            print(f"Skipping {skipped} already-tagged image(s). Use --force to re-tag.\n")
    else:
        images = all_images

    if not images:
        print("Nothing to process.")
        if not args.rename_folder:
            return

    total = len(images)
    processed_meta = []
    for n, img in enumerate(images, 1):
        print(f"  [{n}/{total}] {img.name}")
        try:
            meta = analyze_image(img, vision_model, text_model, roll, args.verbose)
            if args.dry_run:
                print(f"    category: {meta['category']}")
                print(f"    tags:     {', '.join(meta['tags'])}")
                print(f"    desc:     {meta['description']}")
                print(f"    → {img.stem}.xmp  [dry-run, not written]\n")
            else:
                xmp_path = write_xmp(img, meta, roll)
                print(f"    → {xmp_path.name}\n")
                processed_meta.append(meta)
        except Exception as e:
            print(f"  ✗ error: {e}\n")

    if processed_meta:
        write_roll_summary(folder, processed_meta, roll, vision_model, text_model)

    # Build HTML from every image that has an XMP sidecar (includes prior runs)
    html_pairs = [
        (img, _read_xmp_meta(img.with_suffix(".xmp")))
        for img in sorted(f for f in folder.iterdir()
                          if f.is_file() and f.suffix.lower() in IMAGE_EXTS)
        if img.with_suffix(".xmp").exists()
    ]
    if html_pairs:
        write_roll_html(folder, html_pairs, roll)

    if args.rename_folder:
        new_name = build_folder_name(roll)
        if not new_name:
            print("Cannot rename: no usable roll metadata (need date, film, or location).")
        else:
            new_path = folder.parent / new_name
            if new_path == folder:
                print(f"Folder name unchanged: {folder.name}")
            elif new_path.exists():
                print(f"Cannot rename: '{new_name}' already exists in {folder.parent}")
            elif args.dry_run:
                print(f"[dry-run] Would rename: '{folder.name}' → '{new_name}'")
            else:
                folder.rename(new_path)
                print(f"Renamed: '{folder.name}' → '{new_name}'")


def main():
    parser = argparse.ArgumentParser(
        description="Tag analog film scans with AI-generated XMP metadata."
    )
    parser.add_argument(
        "folders",
        metavar="DIR",
        nargs="+",
        help="Folder(s) containing scans. Pass a parent folder to process all sub-rolls.",
    )
    parser.add_argument(
        "--init",
        action="store_true",
        help="Run interactive roll setup before processing.",
    )
    parser.add_argument(
        "--model",
        default="llama3.2-vision:11b",
        metavar="MODEL",
        help="Ollama vision model (default: llama3.2-vision:11b).",
    )
    parser.add_argument(
        "--text-model",
        default=None,
        metavar="MODEL",
        help="Ollama text model for synthesis (default: same as --model).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be written without creating any XMP files.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-tag images that already have an XMP sidecar.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print vision description and full metadata for each image.",
    )
    parser.add_argument(
        "--rename-folder",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Rename the folder to date_film_location after processing (default: on).",
    )
    args = parser.parse_args()

    vision_model = args.model
    text_model = args.text_model or args.model

    # ── Resolve target folders ────────────────────────────────────────────────
    if args.init:
        init_folders = [Path(f).expanduser().resolve() for f in args.folders]

        # Auto-expand: single parent with no images → subfolders
        if len(init_folders) == 1:
            p = init_folders[0]
            p.mkdir(parents=True, exist_ok=True)
            has_images = p.is_dir() and any(
                f.suffix.lower() in IMAGE_EXTS for f in p.iterdir() if f.is_file()
            )
            if not has_images:
                subs = sorted(
                    d for d in p.iterdir()
                    if d.is_dir() and not d.name.startswith(".")
                    and any(f.suffix.lower() in IMAGE_EXTS for f in d.iterdir() if f.is_file())
                )
                if subs:
                    print(f"No images in '{p.name}' — found {len(subs)} sub-folder(s):")
                    for d in subs:
                        print(f"  {d.name}")
                    print()
                    init_folders = subs

        if len(init_folders) == 1:
            init_folders[0].mkdir(parents=True, exist_ok=True)
            if not run_roll_setup(init_folders[0]):
                return
        else:
            for i, folder in enumerate(init_folders):
                folder.mkdir(parents=True, exist_ok=True)
                print(f"\n── [{i + 1}/{len(init_folders)}] {folder.name} {'─' * max(0, 50 - len(folder.name))}")
                run_roll_setup(folder, prompt_process=False)
            ans = input(f"\nStart processing all {len(init_folders)} folder(s) now? [Y/n] ").strip().lower()
            if ans not in ("", "y", "yes"):
                print("   Run:   python3 contact.py " + " ".join(str(f) for f in init_folders) + "\n")
                return

        folders = init_folders
    else:
        folders = [Path(f).expanduser().resolve() for f in args.folders]
        for f in folders:
            if not f.is_dir():
                parser.error(f"not a directory: {f}")

        # Auto-expand: single folder with no direct images → process subdirectories
        if len(folders) == 1:
            p = folders[0]
            has_images = any(
                f.suffix.lower() in IMAGE_EXTS for f in p.iterdir() if f.is_file()
            )
            if not has_images:
                sub_with_images = sorted(
                    d for d in p.iterdir()
                    if d.is_dir()
                    and not d.name.startswith(".")
                    and any(f.suffix.lower() in IMAGE_EXTS
                            for f in d.iterdir() if f.is_file())
                )
                if sub_with_images:
                    print(f"No images in '{p.name}' — found {len(sub_with_images)} sub-folder(s):")
                    for d in sub_with_images:
                        print(f"  {d.name}")
                    print()
                    folders = sub_with_images

    # ── Start Ollama once for all folders ─────────────────────────────────────
    if args.dry_run:
        print("[dry-run] No XMP files will be written.\n")
    print(f"Vision model : {vision_model}")
    print(f"Text model   : {text_model}")
    print()

    already_running = ollama_ready()
    ollama_proc = None
    if not already_running:
        print("Starting Ollama…")
        ollama_proc = subprocess.Popen(
            ["ollama", "serve"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        if not wait_for_ollama():
            print("Error: Ollama failed to start.")
            ollama_proc.terminate()
            return

    try:
        for i, folder in enumerate(folders):
            if len(folders) > 1:
                print(f"── [{i + 1}/{len(folders)}] {folder.name} {'─' * max(0, 50 - len(folder.name))}")
            process_folder(folder, args, vision_model, text_model)
    finally:
        if ollama_proc:
            print("Stopping Ollama…")
            ollama_proc.terminate()
            ollama_proc.wait()


if __name__ == "__main__":
    main()
