#!/usr/bin/env python3
"""
contact.py
──────────
Tags analog film scans with AI-generated metadata and writes XMP sidecar files
readable by Lightroom, darktable, Finder, and Spotlight.

Roll-level metadata (film stock, camera, lens, date, location) is provided via
a roll.yaml file in the scan folder. Per-frame content (description, tags,
category) is generated by a local Ollama vision model.

Usage:
    python3 contact.py --init ~/scans/tuscany/   # launch interactive roll setup
    python3 contact.py ~/scans/tuscany/           # tag all images in folder
    python3 contact.py ~/scans/tuscany/ --dry-run
    python3 contact.py ~/scans/tuscany/ --verbose
    python3 contact.py ~/scans/tuscany/ --force   # re-tag already tagged images
"""

import argparse
import base64
import json
import re
import subprocess
import tempfile
import time
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

IMAGE_EXTS = {".tif", ".tiff", ".jpg", ".jpeg", ".png"}
OLLAMA_BASE = "http://localhost:11434"
VALID_CATEGORIES = {
    "landscape", "portrait", "street", "architecture",
    "nature", "abstract", "other",
}
SYNTHESIS_KEYS = {"CATEGORY", "TAGS", "DESCRIPTION"}

KNOWN_FILM_STOCKS = [
    "Kodak Portra 160", "Kodak Portra 400", "Kodak Portra 800",
    "Kodak Gold 200", "Kodak Ultramax 400", "Kodak Ektar 100",
    "Kodak ColorPlus 200", "Kodak Tri-X 400",
    "Fujifilm Superia 400", "Fujifilm Pro 400H",
    "Fujifilm Velvia 50", "Fujifilm Provia 100F",
    "Ilford HP5 Plus", "Ilford Delta 100", "Ilford FP4 Plus", "Ilford XP2 Super",
    "Lomography Color Negative 400", "CineStill 800T", "CineStill 50D",
]

KNOWN_CAMERAS = [
    "Nikon F3", "Nikon FM2", "Nikon F100",
    "Canon AE-1", "Canon AE-1 Program", "Canon F-1", "Canon EOS 1V",
    "Pentax K1000", "Pentax 645N",
    "Leica M2", "Leica M6", "Leica M7",
    "Contax G2", "Contax T2",
    "Olympus OM-1", "Olympus Stylus Epic",
    "Minolta X-700", "Yashica Mat-124G",
    "Hasselblad 500C/M", "Mamiya RB67",
]

HISTORY_PATH = Path.home() / ".config" / "contact" / "history.json"


# ── Ollama helpers ────────────────────────────────────────────────────────────


def ollama_ready() -> bool:
    try:
        urllib.request.urlopen(f"{OLLAMA_BASE}/api/tags", timeout=2)
        return True
    except Exception:
        return False


def wait_for_ollama(timeout: int = 30) -> bool:
    for _ in range(timeout):
        if ollama_ready():
            return True
        time.sleep(1)
    return False


# ── Roll manifest ─────────────────────────────────────────────────────────────


def _load_history() -> dict:
    base: dict = {"film": {}, "camera": {}, "lens": {}, "location": {}, "subjects": {}, "lab": {}, "lab_notes": {}}
    try:
        if HISTORY_PATH.exists():
            data = json.loads(HISTORY_PATH.read_text(encoding="utf-8"))
            for key in base:
                data.setdefault(key, {})
            return data
    except Exception:
        pass
    return base


def _save_history(history: dict) -> None:
    try:
        HISTORY_PATH.parent.mkdir(parents=True, exist_ok=True)
        HISTORY_PATH.write_text(json.dumps(history, indent=2), encoding="utf-8")
    except Exception:
        pass


def _record(history: dict, key: str, value: str) -> None:
    if not value:
        return
    entry = history[key].get(value, {"count": 0, "last": ""})
    entry["count"] += 1
    entry["last"] = datetime.now().strftime("%Y-%m-%d")
    history[key][value] = entry


def _history_sorted(history: dict, key: str) -> list:
    items = history.get(key, {})
    return sorted(items, key=lambda v: items[v]["last"], reverse=True)


def _suggestions(known: list, history_items: list) -> list:
    used = set(history_items)
    cap = max(0, 10 - len(history_items))
    return [k for k in known if k not in used][:cap]


def _choose(label: str, options: list, current: str = "", history_items: list | None = None) -> str:
    history_items = history_items or []
    print(f"\n{label}")
    all_shown: list = []

    if history_items:
        print("  ── yours ──")
        for item in history_items:
            print(f"  {len(all_shown) + 1:2}. {item}")
            all_shown.append(item)
        if options:
            print("  ── suggestions ──")
            for item in options:
                print(f"  {len(all_shown) + 1:2}. {item}")
                all_shown.append(item)
    else:
        for item in options:
            print(f"  {len(all_shown) + 1:2}. {item}")
            all_shown.append(item)

    default = current or (history_items[0] if history_items else "")
    if all_shown:
        hint = f'keep "{default}"' if default else "skip"
        print(f"  → Enter a number, type your own, or press Enter to {hint}.")
    raw = input("  > ").strip()
    if not raw:
        return default
    if raw.isdigit() and all_shown:
        idx = int(raw) - 1
        if 0 <= idx < len(all_shown):
            return all_shown[idx]
    return raw


def _ask(label: str, current: str = "", hint: str = "") -> str:
    suffix = f" [{current}]" if current else (f" ({hint})" if hint else "")
    raw = input(f"\n{label}{suffix}: ").strip()
    return raw if raw else current


def _split_list_field(s: str) -> list[str]:
    """Split a pipe-separated multi-value field into a list of stripped items."""
    return [v.strip() for v in s.split("|") if v.strip()] if s else []


def _join_list_field(items: list[str]) -> str:
    return " | ".join(items)


def _choose_multi(label: str, history_items: list, current: list | None = None, max_history: int = 0) -> list:
    """Toggleable checklist backed by history, with free-text additions."""
    if max_history:
        history_items = history_items[:max_history]
    in_history = set(history_items)
    extras = [i for i in (current or []) if i not in in_history]
    all_items: list = extras + list(history_items)
    checked: set = set(current or [])

    print(f"\n{label}")
    print("  Toggle by number, type a new entry, or press Enter when done.")
    while True:
        print()
        if all_items:
            for idx, item in enumerate(all_items, 1):
                mark = "x" if item in checked else " "
                print(f"  [{mark}] {idx:2}. {item}")
        else:
            print("  (no previous entries — type to add)")
        raw = input("\n  > ").strip()
        if not raw:
            break
        if raw.isdigit():
            i = int(raw) - 1
            if 0 <= i < len(all_items):
                item = all_items[i]
                if item in checked:
                    checked.discard(item)
                else:
                    checked.add(item)
        else:
            if raw in all_items:
                checked.add(raw)
            else:
                all_items.append(raw)
                checked.add(raw)
    return [item for item in all_items if item in checked]


def run_roll_setup(folder: Path, prompt_process: bool = True) -> bool:
    path = folder / "roll.yaml"
    existing = load_roll_yaml(folder) if path.exists() else {}
    action = "Editing" if existing else "Setting up"
    print(f"\n{action} roll for: {folder}\n")

    history = _load_history()

    film_hist = _history_sorted(history, "film")
    film      = _choose("Film stock:", _suggestions(KNOWN_FILM_STOCKS, film_hist),
                        existing.get("film", ""), history_items=film_hist)

    cam_hist  = _history_sorted(history, "camera")
    camera    = _choose("Camera:", _suggestions(KNOWN_CAMERAS, cam_hist),
                        existing.get("camera", ""), history_items=cam_hist)

    lens_list = _choose_multi(
        "Lenses:",
        history_items=_history_sorted(history, "lens"),
        current=_split_list_field(existing.get("lens", "")),
    )
    lens = _join_list_field(lens_list)

    default_date = existing.get("date", "") or datetime.now().strftime("%Y-%m")
    date     = _ask("Date (YYYY-MM or YYYY-MM-DD)", existing.get("date", ""), default_date) or default_date

    loc_list = _choose_multi(
        "Locations:",
        history_items=_history_sorted(history, "location"),
        current=_split_list_field(existing.get("location", "")),
        max_history=10,
    )
    location = _join_list_field(loc_list)

    subj_list = _choose_multi(
        "Subjects (people, pets, or landmarks):",
        history_items=_history_sorted(history, "subjects"),
        current=_split_list_field(existing.get("subjects", "")),
        max_history=10,
    )
    subjects = _join_list_field(subj_list)

    lab_hist  = _history_sorted(history, "lab")
    if lab_hist:
        lab = _choose("Lab:", [], existing.get("lab", ""), history_items=lab_hist)
    else:
        lab = _ask("Lab", existing.get("lab", ""), "e.g. Mein Film Lab")

    lab_notes_hist = _history_sorted(history, "lab_notes")
    if lab_notes_hist:
        lab_notes = _choose("Lab instructions:", [], existing.get("lab_notes", ""), history_items=lab_notes_hist)
    else:
        lab_notes = _ask("Lab instructions", existing.get("lab_notes", ""), "e.g. push 1 stop")

    notes    = _ask("Notes", existing.get("notes", ""))
    label    = _ask("Label (optional)", existing.get("label", ""), "page title and folder suffix, e.g. Oslo Summer 2024")

    _record(history, "film",      film)
    _record(history, "camera",    camera)
    for _lens in lens_list:
        _record(history, "lens", _lens)
    for _loc in loc_list:
        _record(history, "location", _loc)
    for _subj in subj_list:
        _record(history, "subjects", _subj)
    _record(history, "lab",       lab)
    _record(history, "lab_notes", lab_notes)
    _save_history(history)

    # Preserve any generated section from a prior tagging run
    generated_section = ""
    if path.exists():
        content = path.read_text(encoding="utf-8")
        idx = content.find(GENERATED_MARKER)
        if idx != -1:
            generated_section = "\n" + content[idx:]

    yaml_lines = (
        "# Roll manifest\n"
        f'film:       "{film}"\n'
        f'camera:     "{camera}"\n'
        f'lens:       "{lens}"\n'
        f'date:       "{date}"\n'
        f'location:   "{location}"\n'
        f'subjects:   "{subjects}"\n'
        f'lab:        "{lab}"\n'
        f'lab_notes:  "{lab_notes}"\n'
        f'notes:      "{notes}"\n'
        + (f'label:      "{label}"\n' if label else "")
    )
    path.write_text(yaml_lines + generated_section, encoding="utf-8")

    print(f"\n✓  Saved: {path}")
    if not prompt_process:
        return True
    ans = input("\nStart processing now? [Y/n] ").strip().lower()
    if ans not in ("", "y", "yes"):
        print(f"   Run:   python3 contact.py {folder}\n")
        return False
    return True


def load_roll_yaml(folder: Path) -> dict:
    path = folder / "roll.yaml"
    if not path.exists():
        return {}
    result = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.split("#")[0].strip()
        if not line:
            continue
        key, sep, value = line.partition(":")
        if sep:
            result[key.strip().lower()] = value.strip().strip('"').strip("'")
    return result


# ── Image helpers ─────────────────────────────────────────────────────────────


def _load_image_b64(path: Path, max_pixels: int = 1500) -> str:
    """Return base64-encoded image, downscaled via macOS sips to speed up inference."""
    try:
        with tempfile.NamedTemporaryFile(suffix=".jpg", delete=False) as tmp:
            tmp_path = Path(tmp.name)
        result = subprocess.run(
            ["sips", "-Z", str(max_pixels), "-s", "format", "jpeg", str(path), "--out", str(tmp_path)],
            capture_output=True,
            timeout=30,
        )
        if result.returncode == 0 and tmp_path.stat().st_size > 0:
            data = tmp_path.read_bytes()
            tmp_path.unlink(missing_ok=True)
            return base64.b64encode(data).decode()
        tmp_path.unlink(missing_ok=True)
    except Exception:
        pass
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode()


# ── Ollama API calls ──────────────────────────────────────────────────────────


def _call_vision(b64: str, model: str, prompt: str, system: str, options: dict | None = None) -> str:
    body: dict = {
        "model": model,
        "system": system,
        "prompt": prompt,
        "images": [b64],
        "stream": False,
    }
    if options:
        body["options"] = options
    payload = json.dumps(body).encode()
    req = urllib.request.Request(
        f"{OLLAMA_BASE}/api/generate",
        data=payload,
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=300) as resp:
        return json.loads(resp.read())["response"].strip()


def _call_text(model: str, prompt: str, system: str, options: dict | None = None) -> str:
    body: dict = {
        "model": model,
        "system": system,
        "prompt": prompt,
        "stream": False,
    }
    if options:
        body["options"] = options
    payload = json.dumps(body).encode()
    req = urllib.request.Request(
        f"{OLLAMA_BASE}/api/generate",
        data=payload,
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=60) as resp:
        return json.loads(resp.read())["response"].strip()


# ── Prompts ───────────────────────────────────────────────────────────────────


VISION_SYSTEM = (
    "You are an image analysis assistant. "
    "Describe what you see accurately and in detail."
)

VISION_PROMPT = (
    "Describe the content of this photograph: subject, composition, lighting, and setting. "
    "Be specific and concrete. Describe only what is visually present — "
    "do not infer mood, atmosphere, or emotional tone. "
    "Do not start with 'The image shows' — just describe directly."
)

VISION_PROMPT_FALLBACK = (
    "In one or two sentences, name the main subject and setting of this photograph. "
    "Be brief and concrete."
)

SYNTHESIS_SYSTEM = (
    "You are a metadata assistant for analog film photography. "
    "You output exactly three lines in KEY: VALUE format and nothing else."
)

SYNTHESIS_PROMPT_TMPL = """\
Output exactly these three lines — nothing else:

CATEGORY: <exactly one of: landscape, portrait, street, architecture, nature, abstract, other>
TAGS: <up to 12 comma-separated descriptive keywords>
DESCRIPTION: <2-3 sentences describing what is in the scene>

{vision_section}

Rules:
- CATEGORY: portrait means the face of a person is clearly visible and is the primary subject — \
a figure seen from behind, at a distance, or without a visible face is NOT a portrait; \
landscape = outdoor scenery or countryside where no person dominates; \
street = candid scene in a public urban setting with people or activity; \
architecture = a building or structure is the main subject; \
nature = plants, animals, or natural setting without human structures; \
abstract = pattern or texture is the subject with no recognisable scene; \
other = anything not covered above
- TAGS must be extracted directly from the visual description — do not add any subject, \
person, animal, or object that is not explicitly mentioned in the visual description; \
if you are unsure whether something is present, omit it; \
list visible physical subjects first (people by generic type only: man, woman, child, group — \
never proper names; then other objects and setting); \
only then add lighting qualities — only if clearly visible, using these definitions: \
'natural light' (daylight is the apparent source), \
'window light' (a window is the light source), \
'golden hour' (warm orange or yellow low-angle sunlight is visible — not just any outdoor light), \
'bokeh' (background is visibly blurred), \
'high contrast' (extreme difference between light and shadow areas)
- DESCRIPTION: describe only subjects and details present in the visual description above — \
do not introduce people, animals, or objects not mentioned there; \
factual; no "The image shows" phrasing; \
do not mention film, grain, or equipment; \
refer to people generically (a man, a woman, two people) — do not use proper names; \
do not describe mood, atmosphere, or emotional tone — avoid words like peaceful, serene, \
calm, relaxed, cozy, warm, tranquil, joyful, melancholic, intimate"""


# ── Repetition guard ──────────────────────────────────────────────────────────


def _is_repetitive(text: str) -> bool:
    # Degenerate symbol runs (soft hyphens, em dashes, ellipses)
    for sym, limit in [("—", 15), ("…", 8), (" .. ", 6), ("\xad", 10)]:
        if text.count(sym) > limit:
            return True

    # Sentence-level repetition: any sentence appearing 3+ times
    sentences = [s.strip() for s in re.split(r'(?<=[.!?])\s+|\n', text) if len(s.strip()) > 20]
    if sentences:
        sc: dict[str, int] = {}
        for s in sentences:
            sc[s] = sc.get(s, 0) + 1
        if max(sc.values()) >= 3:
            return True

    # 4-gram repetition: repeated phrases
    words = text.split()
    if len(words) >= 12:
        ngrams = [" ".join(words[i:i+4]) for i in range(len(words) - 3)]
        nc: dict[str, int] = {}
        for ng in ngrams:
            nc[ng] = nc.get(ng, 0) + 1
        if max(nc.values()) >= 3:
            return True

    # Word-level frequency (original check)
    clean = [w.strip(",.;:!?\"'()[]") for w in words]
    clean = [w for w in clean if w]
    if len(clean) < 6:
        return False
    wc: dict[str, int] = {}
    for w in clean:
        wc[w] = wc.get(w, 0) + 1
    return max(wc.values()) / len(clean) >= 0.35


# ── Synthesis parser ──────────────────────────────────────────────────────────


def parse_synthesis(text: str) -> dict:
    result: dict = {}
    for line in text.strip().splitlines():
        key, sep, value = line.partition(":")
        k = key.strip().upper()
        if sep and k in SYNTHESIS_KEYS:
            result[k.lower()] = value.strip()

    tags_raw = result.get("tags", "")
    seen: set = set()
    tags: list = []
    for t in tags_raw.split(","):
        t = t.strip().lower()
        if t and t not in seen:
            seen.add(t)
            tags.append(t)
    result["tags"] = tags

    if result.get("category", "") not in VALID_CATEGORIES:
        result["category"] = "other"

    return result


_PERSON_TERMS = {
    "man", "woman", "child", "boy", "girl", "person", "people",
    "couple", "group", "baby", "infant", "toddler", "teenager",
}

_PERSON_PLURALS = {
    "man": "men", "woman": "women", "child": "children", "person": "people",
}


def _person_forms(term: str) -> set:
    return {term, term + "s", _PERSON_PLURALS.get(term, term + "s")}


def _has_person(text: str) -> bool:
    t = text.lower()
    return any(
        re.search(r"\b" + re.escape(f) + r"\b", t)
        for term in _PERSON_TERMS
        for f in _person_forms(term)
    )


def _drop_phantom_people(tags: list, vision: str) -> list:
    """Remove person-type tags not supported by a word-boundary match in the vision text."""
    vision_lower = vision.lower()
    result = []
    for tag in tags:
        if tag not in _PERSON_TERMS:
            result.append(tag)
            continue
        if any(re.search(r"\b" + re.escape(f) + r"\b", vision_lower) for f in _person_forms(tag)):
            result.append(tag)
    return result


_VISION_OPENER = re.compile(
    r"^(the (main subject|photograph|image|photo)( of this (photograph|image|photo))?"
    r"( (shows?|depicts?|captures?|is ))?"
    r"|this (image|photograph|photo) (shows?|depicts?|is ))",
    re.I,
)


def _vision_as_desc(vision: str) -> str:
    """Strip common opener phrases from a vision description for use as a fallback."""
    text = _VISION_OPENER.sub("", vision).strip()
    return text[0].upper() + text[1:] if text else vision


def _fix_phantom_desc(description: str, vision: str) -> str:
    """Remove sentences that introduce person terms absent from the vision description.

    If vision already mentions any person, the synthesis description is trusted as-is.
    If vision has no people, any sentence mentioning a person is a phantom and is dropped.
    Falls back to a cleaned vision description if all sentences were phantom.
    """
    if not description or _has_person(vision):
        return description
    sentences = re.split(r"(?<=[.!?])\s+", description.strip())
    clean = [s for s in sentences if not _has_person(s)]
    return " ".join(clean) if clean else _vision_as_desc(vision)


# ── XMP writer ────────────────────────────────────────────────────────────────


def _xe(s: str) -> str:
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def write_xmp(image_path: Path, meta: dict, roll: dict) -> Path:
    tags_xml = "\n".join(
        f"      <rdf:li>{_xe(t)}</rdf:li>" for t in meta.get("tags", [])
    )

    def field(tag: str, value: str) -> str:
        return f"      <{tag}>{_xe(value)}</{tag}>\n" if value else ""

    xmp = (
        '<?xpacket begin="\ufeff" id="W5M0MpCehiHzreSzNTczkc9d"?>\n'
        '<x:xmpmeta xmlns:x="adobe:ns:meta/">\n'
        '  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">\n'
        '    <rdf:Description rdf:about=""\n'
        '      xmlns:dc="http://purl.org/dc/elements/1.1/"\n'
        '      xmlns:xmp="http://ns.adobe.com/xap/1.0/"\n'
        '      xmlns:Iptc4xmpCore="http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/"\n'
        '      xmlns:film="http://ns.contact.local/1.0/">\n'
        + field("dc:description", meta.get("description", ""))
        + "      <dc:subject>\n"
        + "        <rdf:Bag>\n"
        + tags_xml + "\n"
        + "        </rdf:Bag>\n"
        + "      </dc:subject>\n"
        + field("xmp:CreateDate", roll.get("date", ""))
        + field("Iptc4xmpCore:Location", roll.get("location", ""))
        + field("film:stock", roll.get("film", ""))
        + field("film:camera", roll.get("camera", ""))
        + field("film:lens", roll.get("lens", ""))
        + field("film:notes", roll.get("notes", ""))
        + field("film:category", meta.get("category", "other"))
        + field("film:visionRaw", meta.get("vision_raw", ""))
        + field("film:processedAt", datetime.now(timezone.utc).isoformat())
        + '    </rdf:Description>\n'
        + '  </rdf:RDF>\n'
        + '</x:xmpmeta>\n'
        + '<?xpacket end="w"?>'
    )

    xmp_path = image_path.with_suffix(".xmp")
    xmp_path.write_text(xmp, encoding="utf-8")
    return xmp_path


def _xe_decode(s: str) -> str:
    return (
        s.replace("&quot;", '"')
        .replace("&gt;", ">")
        .replace("&lt;", "<")
        .replace("&amp;", "&")
    )


def _read_xmp_meta(xmp_path: Path) -> dict:
    """Extract description, tags, and category from an XMP sidecar we wrote."""
    try:
        content = xmp_path.read_text(encoding="utf-8")
    except Exception:
        return {"description": "", "category": "other", "tags": []}
    desc_m = re.search(r"<dc:description>(.*?)</dc:description>", content, re.DOTALL)
    cat_m  = re.search(r"<film:category>([^<]*)</film:category>", content)
    tags   = re.findall(r"<rdf:li>([^<]+)</rdf:li>", content)
    return {
        "description": _xe_decode(desc_m.group(1).strip()) if desc_m else "",
        "category":    cat_m.group(1).strip() if cat_m else "other",
        "tags":        [_xe_decode(t) for t in tags],
    }


# ── Main pipeline ─────────────────────────────────────────────────────────────


# Three escalating attempts: full prompt → short fallback → very short fallback
_VISION_ATTEMPTS = [
    (VISION_PROMPT,          {"num_predict": 300, "repeat_penalty": 1.3}),
    (VISION_PROMPT_FALLBACK, {"num_predict": 100, "repeat_penalty": 1.5}),
    (VISION_PROMPT_FALLBACK, {"num_predict":  60, "repeat_penalty": 1.8}),
]
_SYNTH_OPTS = {"num_predict": 200, "repeat_penalty": 1.1}


def analyze_image(
    path: Path,
    vision_model: str,
    text_model: str,
    roll: dict,
    verbose: bool,
) -> dict:
    b64 = _load_image_b64(path)

    visual_desc = None
    for attempt, (v_prompt, v_opts) in enumerate(_VISION_ATTEMPTS, 1):
        try:
            result = _call_vision(b64, vision_model, v_prompt, VISION_SYSTEM, v_opts)
        except Exception as e:
            raise RuntimeError(f"vision stage failed (attempt {attempt}): {e}") from e
        if not _is_repetitive(result):
            if attempt > 1:
                print(f"    [vision] succeeded on attempt {attempt}")
            visual_desc = result
            break
        if attempt < len(_VISION_ATTEMPTS):
            print(f"    [vision] loop on attempt {attempt} — retrying")

    if visual_desc is None:
        print("    [vision] all attempts looped — skipping")
        return {
            "category": "other",
            "tags": [],
            "description": "",
            "vision_raw": "(vision model produced repetitive output — skipped)",
        }

    if verbose:
        print(f"    [vision] {visual_desc}")

    synthesis_prompt = SYNTHESIS_PROMPT_TMPL.format(
        vision_section=f"Visual description: {visual_desc}",
    )

    try:
        raw_synthesis = _call_text(text_model, synthesis_prompt, SYNTHESIS_SYSTEM, _SYNTH_OPTS)
    except Exception as e:
        raise RuntimeError(f"synthesis stage failed: {e}") from e

    meta = parse_synthesis(raw_synthesis)
    meta["tags"]        = _drop_phantom_people(meta.get("tags", []), visual_desc)
    meta["description"] = _fix_phantom_desc(meta.get("description", ""), visual_desc)

    if verbose:
        print(f"    [category]    {meta.get('category', '?')}")
        print(f"    [tags]        {', '.join(meta.get('tags', []))}")
        print(f"    [description] {meta.get('description', '')}")

    return {
        "category": meta.get("category", "other"),
        "tags": meta.get("tags", []),
        "description": meta.get("description", ""),
        "vision_raw": visual_desc,
    }


# ── Roll summary ──────────────────────────────────────────────────────────────


GENERATED_MARKER = "# ── Generated by contact"

ROLL_SUMMARY_SYSTEM = "You are a photography archivist. Write concise, factual roll summaries."

ROLL_SUMMARY_PROMPT_TMPL = """\
Roll metadata:
  Location: {location}
  Subjects: {subjects}
  Date: {date}

Frame descriptions:
{descriptions}

Write 2-3 sentences summarising this roll as a whole. \
You may reference subject names from the roll metadata as general context for the roll \
(e.g. "a roll with Felix and Bea"), but do not attribute specific actions, poses, or \
positions to named individuals — you cannot identify who is in which frame; \
describe people in individual frames generically (a man, a woman, the group). \
Anchor the location to the roll metadata — do not infer or add location details not stated there. \
Describe only what is directly stated in the frame descriptions — do not speculate. \
Do not describe mood, atmosphere, or emotional qualities. \
Do not mention film, camera, equipment, or technical qualities."""


def _generate_roll_prose(all_meta: list, roll: dict, text_model: str) -> str:
    descs = [
        m["description"] for m in all_meta
        if m.get("description") and not m.get("vision_raw", "").startswith("(vision")
    ]
    if not descs:
        return ""
    prompt = ROLL_SUMMARY_PROMPT_TMPL.format(
        location=", ".join(_split_list_field(roll.get("location", ""))) or "not specified",
        subjects=", ".join(_split_list_field(roll.get("subjects", ""))) or "not specified",
        date=roll.get("date", "not specified"),
        descriptions="\n".join(f"- {d}" for d in descs[:20]),
    )
    try:
        return _call_text(text_model, prompt, ROLL_SUMMARY_SYSTEM, {"num_predict": 150, "repeat_penalty": 1.1})
    except Exception:
        return ""


def write_roll_summary(
    folder: Path, all_meta: list, roll: dict, vision_model: str, text_model: str
) -> None:
    cat_counts: dict[str, int] = {}
    tag_counts: dict[str, int] = {}
    for m in all_meta:
        cat = m.get("category", "other")
        cat_counts[cat] = cat_counts.get(cat, 0) + 1
        for t in m.get("tags", []):
            tag_counts[t] = tag_counts.get(t, 0) + 1

    categories_str = ", ".join(
        f"{cat}: {n}" for cat, n in sorted(cat_counts.items(), key=lambda x: -x[1])
    )
    top_tags_str = ", ".join(
        t for t, _ in sorted(tag_counts.items(), key=lambda x: -x[1])[:12]
    )

    print("Generating roll summary…")
    prose = _generate_roll_prose(all_meta, roll, text_model)

    path = folder / "roll.yaml"
    content = path.read_text(encoding="utf-8") if path.exists() else ""
    idx = content.find(GENERATED_MARKER)
    base = content[:idx].rstrip() + "\n" if idx != -1 else content

    model_line = (
        f'model:      "{vision_model}"\n' if vision_model == text_model
        else f'vision_model: "{vision_model}"\ntext_model:   "{text_model}"\n'
    )
    generated = (
        f"\n{GENERATED_MARKER} ─────────────────────────────────────────────────\n"
        f'processed:  "{datetime.now().strftime("%Y-%m-%d")}"\n'
        + model_line
        + f'frames:     "{len(all_meta)}"\n'
        f'categories: "{categories_str}"\n'
        f'top_tags:   "{top_tags_str}"\n'
    )
    if prose:
        generated += f'summary:    "{prose.replace(chr(34), chr(39))}"\n'

    path.write_text(base + generated, encoding="utf-8")
    print(f"  → roll.yaml updated\n")


# ── HTML index ────────────────────────────────────────────────────────────────


def write_roll_html(folder: Path, pairs: list, roll: dict) -> None:
    """pairs: [(image_path, meta), ...]. Reloads roll.yaml to pick up generated summary."""
    full_roll = load_roll_yaml(folder)

    _LIST_FM_FIELDS = {"location", "lens", "subjects"}

    roll_label = full_roll.get("label", "")
    location = full_roll.get("location", "")
    locs = _split_list_field(location)
    first_loc = locs[0] if locs else ""
    if roll_label:
        title = roll_label
    else:
        title_parts = [p for p in [first_loc, full_roll.get("date", "")] if p]
        title = " — ".join(title_parts) if title_parts else folder.name

    # Frontmatter: terminal key/value block (Option B)
    _DOT = ' <span class="fm-sep">\u00b7</span> '

    def _fm_join(key):
        v = full_roll.get(key, "")
        if not v:
            return ""
        items = _split_list_field(v) if key in _LIST_FM_FIELDS else [v]
        return _DOT.join(_xe(i) for i in items)

    lab_parts = [p for p in [full_roll.get("lab", ""), full_roll.get("lab_notes", "")] if p]
    lab_val = _DOT.join(_xe(p) for p in lab_parts)

    fm_rows_data = [
        ("DATE",  _xe(full_roll.get("date",   ""))),
        ("FILM",  _xe(full_roll.get("film",   ""))),
        ("CAM",   _xe(full_roll.get("camera", ""))),
        ("LENS",  _fm_join("lens")),
        ("LOC",   _fm_join("location")),
        ("SUBJ",  _fm_join("subjects")),
        ("LAB",   lab_val),
        ("NOTES", _xe(full_roll.get("notes",  ""))),
    ]
    fm_rows_html = "".join(
        f'<div class="fm-row"><span class="fm-key">{k}</span>'
        f'<span class="fm-val">{v}</span></div>'
        for k, v in fm_rows_data if v
    )
    summary = full_roll.get("summary", "")
    if summary and fm_rows_html:
        fm_rows_html += (
            '<div class="fm-row fm-summ-row">'
            '<span class="fm-key fm-summ-key">+</span>'
            f'<span class="fm-summ-val" style="display:none">'
            f'<span class="fm-summ-label">AI summary</span>  {_xe(summary)}'
            '</span>'
            '</div>'
        )
    frontmatter_html = f'<div class="fm-strip">{fm_rows_html}</div>' if fm_rows_html else ""

    cards = []
    for img_path, meta in pairs:
        tags_str = ", ".join(meta.get("tags", []))
        search_data = " ".join([
            img_path.name,
            meta.get("description", ""),
            meta.get("category", ""),
            tags_str,
        ]).lower()
        cards.append(
            f'<div class="card" data-search="{_xe(search_data)}" data-img="{_xe(img_path.name)}"'
            f' data-category="{_xe(meta.get("category", ""))}"'
            f' data-description="{_xe(meta.get("description", ""))}"'
            f' data-tags="{_xe(tags_str)}">'
            f'<button class="star-btn" aria-label="Star">&#9734;</button>'
            f'<img src="{_xe(img_path.name)}" alt="" loading="lazy">'
            f'<div class="card-body">'
            f'<div class="fname">{_xe(img_path.name)}</div>'
            f'</div></div>'
        )

    css = """\
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: system-ui, -apple-system, sans-serif; background: #f0f0f0; color: #1a1a1a; padding: 2rem 1.5rem; }
.header { margin-bottom: 1.5rem; }
.header-top { margin-bottom: .5rem; }
h1 { font-size: 1.4rem; font-weight: 600; }
.fm-strip { font-family: ui-monospace, 'SF Mono', monospace; font-size: .76rem; line-height: 1.8; margin-bottom: .6rem; }
.fm-row { display: flex; gap: 0; }
.fm-key { color: #bbb; min-width: 5ch; margin-right: 1.5ch; flex-shrink: 0; }
.fm-val { color: #444; }
.fm-sep { color: #ccc; margin: 0 .3em; }
#search { width: 100%; display: block; padding: .4rem .7rem; font-size: .85rem; border: 1px solid #ccc; border-radius: 4px; background: #fff; color: #1a1a1a; margin-bottom: .75rem; }
#search:focus { outline: none; border-color: #888; }
.fm-summ-key { cursor: pointer; }
.fm-summ-key:hover { color: #555; }
.fm-summ-val { color: #555; }
.fm-summ-label { color: #bbb; margin-right: .4em; }
.no-results { font-size: .85rem; color: #999; padding: .5rem 0 1rem; display: none; }
.starred-section { margin-bottom: .25rem; }
.starred-label { font-size: .68rem; font-weight: 600; text-transform: uppercase; letter-spacing: .08em; color: #ccc; margin-bottom: .5rem; }
.section-rule { border: none; border-top: 1px solid #e4e4e4; margin: .25rem 0 1rem; }
.grid { columns: 300px; column-gap: 1rem; }
.card { background: #fff; border-radius: 6px; overflow: hidden; position: relative; break-inside: avoid; margin-bottom: 1rem; }
.card img { width: 100%; height: auto; display: block; background: #ddd; cursor: zoom-in; }
.card-body { padding: .5rem .75rem .6rem; }
.fname { font-family: monospace; font-size: .68rem; color: #bbb; }
.star-btn { position: absolute; top: .5rem; right: .5rem; background: rgba(0,0,0,.4); border: none; border-radius: 50%; width: 28px; height: 28px; font-size: .95rem; line-height: 28px; text-align: center; cursor: pointer; color: #fff; opacity: 0; transition: opacity .15s; z-index: 1; }
.card:hover .star-btn, .card.starred .star-btn { opacity: 1; }
.card.starred .star-btn { color: #f0b429; }
#lightbox { display: none; position: fixed; inset: 0; z-index: 1000; flex-direction: column; }
#lightbox.open { display: flex; }
#lb-bg { position: absolute; inset: 0; background: rgba(0,0,0,.92); }
#lb-close { position: absolute; top: 1rem; right: 1rem; background: rgba(255,255,255,.15); border: none; color: #fff; font-size: 1.4rem; width: 36px; height: 36px; border-radius: 50%; cursor: pointer; display: flex; align-items: center; justify-content: center; z-index: 2; }
#lb-main { position: relative; flex: 1; min-height: 0; display: flex; align-items: center; justify-content: center; padding: 1rem 4rem; }
#lb-img { position: relative; max-width: 100%; max-height: 100%; object-fit: contain; border-radius: 2px; z-index: 1; }
#lb-prev, #lb-next { position: absolute; top: 50%; transform: translateY(-50%); background: rgba(255,255,255,.12); border: none; color: #fff; font-size: 2.2rem; width: 52px; height: 72px; border-radius: 4px; cursor: pointer; display: flex; align-items: center; justify-content: center; z-index: 2; }
#lb-prev { left: .5rem; }
#lb-next { right: .5rem; }
#lb-prev:hover, #lb-next:hover, #lb-close:hover { background: rgba(255,255,255,.25); }
#lb-info { position: relative; z-index: 1; background: rgba(0,0,0,.65); border-top: 1px solid rgba(255,255,255,.07); padding: .6rem 1.5rem; display: flex; flex-direction: column; gap: .35rem; }
.lb-top { display: flex; align-items: center; gap: .75rem; }
#lb-star { background: none; border: none; color: #666; font-size: 1rem; cursor: pointer; padding: 0; line-height: 1; }
#lb-star:hover { color: #f0b429; }
#lb-star.on { color: #f0b429; }
#lb-fname { font-family: monospace; font-size: .72rem; color: #666; }
#lb-cat { font-size: .63rem; font-weight: 700; text-transform: uppercase; letter-spacing: .07em; color: #555; background: rgba(255,255,255,.08); padding: 1px 7px; border-radius: 99px; }
#lb-desc { font-size: .83rem; line-height: 1.5; color: #aaa; }
#lb-tags { display: flex; flex-wrap: wrap; gap: 4px; }
.lb-tag { font-size: .67rem; background: rgba(255,255,255,.08); color: #888; padding: 2px 7px; border-radius: 3px; }
"""

    js = """\
<script>
(function(){
  // ── Search ──────────────────────────────────────────────────────────────────
  var searchEl = document.getElementById('search');
  searchEl.addEventListener('keydown', function(e) {
    if (e.key === 'Escape') { searchEl.value = ''; searchEl.dispatchEvent(new Event('input')); searchEl.blur(); }
  });
  var cards = Array.from(document.querySelectorAll('.card'));
  var starredGrid = document.getElementById('starred-grid');
  var mainGrid = document.getElementById('main-grid');
  var starredSection = document.getElementById('starred-section');
  var noRes = document.getElementById('no-results');
  searchEl.addEventListener('input', function(){
    var q = searchEl.value.toLowerCase();
    var visible = 0;
    cards.forEach(function(c){
      var show = !q || c.dataset.search.indexOf(q) !== -1;
      c.style.display = show ? '' : 'none';
      if (show) visible++;
    });
    noRes.style.display = (q && visible === 0) ? 'block' : 'none';
  });

  // ── Stars / pinning ─────────────────────────────────────────────────────────
  var STAR_KEY = 'film-stars:' + window.location.pathname;
  var starred = JSON.parse(localStorage.getItem(STAR_KEY) || '[]');
  function visibleCards() {
    return Array.from(document.querySelectorAll('.card')).filter(function(c){ return c.style.display !== 'none'; });
  }
  function applyStars() {
    cards.forEach(function(card) {
      var on = starred.indexOf(card.dataset.img) !== -1;
      card.classList.toggle('starred', on);
      card.querySelector('.star-btn').innerHTML = on ? '&#9733;' : '&#9734;';
      (on ? starredGrid : mainGrid).appendChild(card);
    });
    starredSection.style.display = starredGrid.children.length ? '' : 'none';
    // Sync lightbox star button
    var lbStarEl = document.getElementById('lb-star');
    if (lbStarEl && lbCard) {
      var on = starred.indexOf(lbCard.dataset.img) !== -1;
      lbStarEl.innerHTML = on ? '&#9733;' : '&#9734;';
      lbStarEl.classList.toggle('on', on);
    }
  }
  applyStars();
  document.querySelectorAll('.star-btn').forEach(function(btn) {
    btn.addEventListener('click', function(e) {
      e.stopPropagation();
      toggleStar(btn.closest('.card').dataset.img);
    });
  });
  function toggleStar(imgName) {
    var i = starred.indexOf(imgName);
    if (i === -1) starred.push(imgName); else starred.splice(i, 1);
    localStorage.setItem(STAR_KEY, JSON.stringify(starred));
    applyStars();
  }

  // ── Lightbox ─────────────────────────────────────────────────────────────────
  var lb = document.getElementById('lightbox');
  var lbImg = document.getElementById('lb-img');
  var lbCard = null;
  function showLbCard(card) {
    lbCard = card;
    lbImg.src = card.querySelector('img').src;
    var on = starred.indexOf(card.dataset.img) !== -1;
    var lbStarEl = document.getElementById('lb-star');
    lbStarEl.innerHTML = on ? '&#9733;' : '&#9734;';
    lbStarEl.classList.toggle('on', on);
    document.getElementById('lb-fname').textContent = card.dataset.img;
    document.getElementById('lb-cat').textContent = card.dataset.category;
    document.getElementById('lb-desc').textContent = card.dataset.description;
    var tagsEl = document.getElementById('lb-tags');
    tagsEl.innerHTML = '';
    (card.dataset.tags || '').split(',').forEach(function(t) {
      t = t.trim();
      if (!t) return;
      var s = document.createElement('span');
      s.className = 'lb-tag';
      s.textContent = t;
      tagsEl.appendChild(s);
    });
  }
  function openLb(card) {
    showLbCard(card);
    lb.classList.add('open');
    document.body.style.overflow = 'hidden';
  }
  function closeLb() { lb.classList.remove('open'); lbImg.src = ''; document.body.style.overflow = ''; }
  function navLb(d) {
    var vc = visibleCards();
    var idx = vc.indexOf(lbCard);
    if (idx === -1) idx = 0;
    showLbCard(vc[(idx + d + vc.length) % vc.length]);
  }
  cards.forEach(function(card) {
    card.querySelector('img').addEventListener('click', function() { openLb(card); });
  });
  document.getElementById('lb-bg').addEventListener('click', closeLb);
  document.getElementById('lb-close').addEventListener('click', closeLb);
  document.getElementById('lb-prev').addEventListener('click', function(){ navLb(-1); });
  document.getElementById('lb-next').addEventListener('click', function(){ navLb(1); });
  document.getElementById('lb-star').addEventListener('click', function(){ if (lbCard) toggleStar(lbCard.dataset.img); });

  // ── Global keyboard ─────────────────────────────────────────────────────────
  document.addEventListener('keydown', function(e) {
    if (lb.classList.contains('open')) {
      if (e.key === 'ArrowLeft' || e.key === 'k') { e.preventDefault(); navLb(-1); }
      if (e.key === 'ArrowRight' || e.key === 'j') { e.preventDefault(); navLb(1); }
      if (e.key === 's' && lbCard) toggleStar(lbCard.dataset.img);
      if (e.key === 'Escape') closeLb();
      return;
    }
    if (e.key === 'Escape' && document.activeElement === searchEl) { searchEl.blur(); return; }
    if ((e.key === 'Enter' || e.key === '/') && document.activeElement !== searchEl) { e.preventDefault(); searchEl.focus(); }
  });

  // ── Summary toggle ───────────────────────────────────────────────────────────
  var summKey = document.querySelector('.fm-summ-key');
  if (summKey) {
    summKey.addEventListener('click', function() {
      var val = this.parentElement.querySelector('.fm-summ-val');
      var open = val.style.display !== 'none';
      val.style.display = open ? 'none' : '';
      this.textContent = open ? '+' : '-';
    });
  }
})();
</script>"""

    html = (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '<meta charset="UTF-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        f"<title>{_xe(title)}</title>\n"
        f"<style>\n{css}\n</style>\n"
        "</head>\n"
        "<body>\n"
        '<div class="header">\n'
        '<div class="header-top">\n'
        f'<h1>{_xe(title)}</h1>\n'
        '</div>\n'
        f"{frontmatter_html}\n"
        '<input type="search" id="search" placeholder="Search frames\u2026" autocomplete="off">\n'
        "</div>\n"
        '<div id="no-results" class="no-results">No frames match.</div>\n'
        '<div id="starred-section" class="starred-section" style="display:none">'
        '<div class="starred-label">Starred</div>'
        '<div id="starred-grid" class="grid"></div>'
        '<hr class="section-rule">'
        '</div>'
        '<div id="main-grid" class="grid">\n'
        + "".join(cards)
        + "\n</div>\n"
        '<div id="lightbox">'
        '<div id="lb-bg"></div>'
        '<button id="lb-close">&#215;</button>'
        '<div id="lb-main">'
        '<button id="lb-prev">&#8249;</button>'
        '<img id="lb-img" alt="">'
        '<button id="lb-next">&#8250;</button>'
        '</div>'
        '<div id="lb-info">'
        '<div class="lb-top"><button id="lb-star">&#9734;</button><span id="lb-fname"></span><span id="lb-cat"></span></div>'
        '<p id="lb-desc"></p>'
        '<div id="lb-tags"></div>'
        '</div>'
        '</div>\n'
        + js
        + "\n</body>\n</html>"
    )

    out = folder / "index.html"
    out.write_text(html, encoding="utf-8")
    print(f"  → index.html")


# ── Folder renaming ───────────────────────────────────────────────────────────


def _slugify(s: str) -> str:
    s = s.lower().strip()
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"[\s_]+", "-", s)
    return re.sub(r"-+", "-", s).strip("-")


def _normalize_date(s: str) -> str:
    """Extract a sortable YYYY-MM or YYYY prefix from any date string."""
    # YYYY-MM where month is valid (avoids matching year ranges like 2020-2023)
    m = re.search(r"\b(\d{4})-(0[1-9]|1[0-2])\b", s)
    if m:
        return f"{m.group(1)}-{m.group(2)}"
    # Fall back to first four-digit year found
    m = re.search(r"\b(\d{4})\b", s)
    if m:
        return m.group(1)
    return ""


def build_folder_name(roll: dict) -> str:
    date = _normalize_date(roll.get("date", "")) or datetime.now().strftime("%Y-%m")
    roll_label = roll.get("label", "")
    if roll_label:
        return "_".join(p for p in [date, _slugify(roll_label)] if p)
    locs = _split_list_field(roll.get("location", ""))
    first_location = locs[0] if locs else ""
    parts = [date, _slugify(roll.get("film", "")), _slugify(first_location)]
    return "_".join(p for p in parts if p)


# ── Main ──────────────────────────────────────────────────────────────────────


def process_folder(folder: Path, args, vision_model: str, text_model: str) -> None:
    """Tag all images in a single folder, write summary + HTML, optionally rename."""
    roll = load_roll_yaml(folder)
    if roll:
        print("Roll metadata:")
        for k, v in roll.items():
            if v:
                print(f"  {k}: {v}")
        print()
    else:
        print("No roll.yaml found — proceeding with content analysis only.\n")

    all_images = sorted(
        f for f in folder.iterdir()
        if f.is_file() and f.suffix.lower() in IMAGE_EXTS
    )

    if not args.force:
        images = [f for f in all_images if not f.with_suffix(".xmp").exists()]
        skipped = len(all_images) - len(images)
        if skipped:
            print(f"Skipping {skipped} already-tagged image(s). Use --force to re-tag.\n")
    else:
        images = all_images

    if not images:
        print("Nothing to process.")
        if not args.rename_folder:
            return

    total = len(images)
    processed_meta = []
    for n, img in enumerate(images, 1):
        print(f"  [{n}/{total}] {img.name}")
        try:
            meta = analyze_image(img, vision_model, text_model, roll, args.verbose)
            if args.dry_run:
                print(f"    category: {meta['category']}")
                print(f"    tags:     {', '.join(meta['tags'])}")
                print(f"    desc:     {meta['description']}")
                print(f"    → {img.stem}.xmp  [dry-run, not written]\n")
            else:
                xmp_path = write_xmp(img, meta, roll)
                print(f"    → {xmp_path.name}\n")
                processed_meta.append(meta)
        except Exception as e:
            print(f"  ✗ error: {e}\n")

    if processed_meta:
        write_roll_summary(folder, processed_meta, roll, vision_model, text_model)

    # Build HTML from every image that has an XMP sidecar (includes prior runs)
    html_pairs = [
        (img, _read_xmp_meta(img.with_suffix(".xmp")))
        for img in sorted(f for f in folder.iterdir()
                          if f.is_file() and f.suffix.lower() in IMAGE_EXTS)
        if img.with_suffix(".xmp").exists()
    ]
    if html_pairs:
        write_roll_html(folder, html_pairs, roll)

    if args.rename_folder:
        new_name = build_folder_name(roll)
        if not new_name:
            print("Cannot rename: no usable roll metadata (need date, film, or location).")
        else:
            new_path = folder.parent / new_name
            if new_path == folder:
                print(f"Folder name unchanged: {folder.name}")
            elif new_path.exists():
                print(f"Cannot rename: '{new_name}' already exists in {folder.parent}")
            elif args.dry_run:
                print(f"[dry-run] Would rename: '{folder.name}' → '{new_name}'")
            else:
                folder.rename(new_path)
                print(f"Renamed: '{folder.name}' → '{new_name}'")


def main():
    parser = argparse.ArgumentParser(
        description="Tag analog film scans with AI-generated XMP metadata."
    )
    parser.add_argument(
        "folders",
        metavar="DIR",
        nargs="+",
        help="Folder(s) containing scans. Pass a parent folder to process all sub-rolls.",
    )
    parser.add_argument(
        "--init",
        action="store_true",
        help="Run interactive roll setup before processing.",
    )
    parser.add_argument(
        "--model",
        default="llama3.2-vision:11b",
        metavar="MODEL",
        help="Ollama vision model (default: llama3.2-vision:11b).",
    )
    parser.add_argument(
        "--text-model",
        default=None,
        metavar="MODEL",
        help="Ollama text model for synthesis (default: same as --model).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be written without creating any XMP files.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-tag images that already have an XMP sidecar.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print vision description and full metadata for each image.",
    )
    parser.add_argument(
        "--rename-folder",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Rename the folder to date_film_location after processing (default: on).",
    )
    args = parser.parse_args()

    vision_model = args.model
    text_model = args.text_model or args.model

    # ── Resolve target folders ────────────────────────────────────────────────
    if args.init:
        init_folders = [Path(f).expanduser().resolve() for f in args.folders]

        # Auto-expand: single parent with no images → subfolders
        if len(init_folders) == 1:
            p = init_folders[0]
            p.mkdir(parents=True, exist_ok=True)
            has_images = p.is_dir() and any(
                f.suffix.lower() in IMAGE_EXTS for f in p.iterdir() if f.is_file()
            )
            if not has_images:
                subs = sorted(
                    d for d in p.iterdir()
                    if d.is_dir() and not d.name.startswith(".")
                    and any(f.suffix.lower() in IMAGE_EXTS for f in d.iterdir() if f.is_file())
                )
                if subs:
                    print(f"No images in '{p.name}' — found {len(subs)} sub-folder(s):")
                    for d in subs:
                        print(f"  {d.name}")
                    print()
                    init_folders = subs

        if len(init_folders) == 1:
            init_folders[0].mkdir(parents=True, exist_ok=True)
            if not run_roll_setup(init_folders[0]):
                return
        else:
            for i, folder in enumerate(init_folders):
                folder.mkdir(parents=True, exist_ok=True)
                print(f"\n── [{i + 1}/{len(init_folders)}] {folder.name} {'─' * max(0, 50 - len(folder.name))}")
                run_roll_setup(folder, prompt_process=False)
            ans = input(f"\nStart processing all {len(init_folders)} folder(s) now? [Y/n] ").strip().lower()
            if ans not in ("", "y", "yes"):
                print("   Run:   python3 contact.py " + " ".join(str(f) for f in init_folders) + "\n")
                return

        folders = init_folders
    else:
        folders = [Path(f).expanduser().resolve() for f in args.folders]
        for f in folders:
            if not f.is_dir():
                parser.error(f"not a directory: {f}")

        # Auto-expand: single folder with no direct images → process subdirectories
        if len(folders) == 1:
            p = folders[0]
            has_images = any(
                f.suffix.lower() in IMAGE_EXTS for f in p.iterdir() if f.is_file()
            )
            if not has_images:
                sub_with_images = sorted(
                    d for d in p.iterdir()
                    if d.is_dir()
                    and not d.name.startswith(".")
                    and any(f.suffix.lower() in IMAGE_EXTS
                            for f in d.iterdir() if f.is_file())
                )
                if sub_with_images:
                    print(f"No images in '{p.name}' — found {len(sub_with_images)} sub-folder(s):")
                    for d in sub_with_images:
                        print(f"  {d.name}")
                    print()
                    folders = sub_with_images

    # ── Start Ollama once for all folders ─────────────────────────────────────
    if args.dry_run:
        print("[dry-run] No XMP files will be written.\n")
    print(f"Vision model : {vision_model}")
    print(f"Text model   : {text_model}")
    print()

    already_running = ollama_ready()
    ollama_proc = None
    if not already_running:
        print("Starting Ollama…")
        ollama_proc = subprocess.Popen(
            ["ollama", "serve"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        if not wait_for_ollama():
            print("Error: Ollama failed to start.")
            ollama_proc.terminate()
            return

    try:
        for i, folder in enumerate(folders):
            if len(folders) > 1:
                print(f"── [{i + 1}/{len(folders)}] {folder.name} {'─' * max(0, 50 - len(folder.name))}")
            process_folder(folder, args, vision_model, text_model)
    finally:
        if ollama_proc:
            print("Stopping Ollama…")
            ollama_proc.terminate()
            ollama_proc.wait()


if __name__ == "__main__":
    main()
