"""
processor/roll.py
─────────────────
Roll manifest (roll.yaml) read/write, history management, terminal UI helpers,
and folder naming utilities.
No internal imports — stdlib only.
"""

import json
import re
from datetime import datetime
from pathlib import Path

# ── Constants ─────────────────────────────────────────────────────────────────

IMAGE_EXTS = {".tif", ".tiff", ".jpg", ".jpeg", ".png"}

KNOWN_FILM_STOCKS = [
    "Kodak Portra 160", "Kodak Portra 400", "Kodak Portra 800",
    "Kodak Gold 200", "Kodak Ultramax 400", "Kodak Ektar 100",
    "Kodak ColorPlus 200", "Kodak Tri-X 400",
    "Fujifilm Superia 400", "Fujifilm Pro 400H",
    "Fujifilm Velvia 50", "Fujifilm Provia 100F",
    "Ilford HP5 Plus", "Ilford Delta 100", "Ilford FP4 Plus", "Ilford XP2 Super",
    "Lomography Color Negative 400", "CineStill 800T", "CineStill 50D",
]

KNOWN_CAMERAS = [
    "Nikon F3", "Nikon FM2", "Nikon F100",
    "Canon AE-1", "Canon AE-1 Program", "Canon F-1", "Canon EOS 1V",
    "Pentax K1000", "Pentax 645N",
    "Leica M2", "Leica M6", "Leica M7",
    "Contax G2", "Contax T2",
    "Olympus OM-1", "Olympus Stylus Epic",
    "Minolta X-700", "Yashica Mat-124G",
    "Hasselblad 500C/M", "Mamiya RB67",
]

HISTORY_PATH = Path.home() / ".config" / "contact" / "history.json"

GENERATED_MARKER = "# ── Generated by contact"


# ── Pure string helpers ───────────────────────────────────────────────────────


def _split_list_field(s: str) -> list[str]:
    """Split a pipe-separated multi-value field into a list of stripped items."""
    return [v.strip() for v in s.split("|") if v.strip()] if s else []


def _join_list_field(items: list[str]) -> str:
    return " | ".join(items)


# ── Folder naming ─────────────────────────────────────────────────────────────


def _slugify(s: str) -> str:
    s = s.lower().strip()
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"[\s_]+", "-", s)
    return re.sub(r"-+", "-", s).strip("-")


def _normalize_date(s: str) -> str:
    """Extract a sortable YYYY-MM or YYYY prefix from any date string."""
    # YYYY-MM where month is valid (avoids matching year ranges like 2020-2023)
    m = re.search(r"\b(\d{4})-(0[1-9]|1[0-2])\b", s)
    if m:
        return f"{m.group(1)}-{m.group(2)}"
    # Fall back to first four-digit year found
    m = re.search(r"\b(\d{4})\b", s)
    if m:
        return m.group(1)
    return ""


def build_folder_name(roll: dict) -> str:
    date = _normalize_date(roll.get("date", "")) or datetime.now().strftime("%Y-%m")
    roll_label = roll.get("label", "")
    if roll_label:
        return "_".join(p for p in [date, _slugify(roll_label)] if p)
    locs = _split_list_field(roll.get("location", ""))
    first_location = locs[0] if locs else ""
    parts = [date, _slugify(roll.get("film", "")), _slugify(first_location)]
    return "_".join(p for p in parts if p)


# ── History ───────────────────────────────────────────────────────────────────


def _load_history() -> dict:
    base: dict = {"film": {}, "camera": {}, "lens": {}, "location": {}, "subjects": {}, "lab": {}, "lab_notes": {}}
    try:
        if HISTORY_PATH.exists():
            data = json.loads(HISTORY_PATH.read_text(encoding="utf-8"))
            for key in base:
                data.setdefault(key, {})
            return data
    except Exception:
        pass
    return base


def _save_history(history: dict) -> None:
    try:
        HISTORY_PATH.parent.mkdir(parents=True, exist_ok=True)
        HISTORY_PATH.write_text(json.dumps(history, indent=2), encoding="utf-8")
    except Exception:
        pass


def _record(history: dict, key: str, value: str) -> None:
    if not value:
        return
    entry = history[key].get(value, {"count": 0, "last": ""})
    entry["count"] += 1
    entry["last"] = datetime.now().strftime("%Y-%m-%d")
    history[key][value] = entry


def _history_sorted(history: dict, key: str) -> list:
    items = history.get(key, {})
    return sorted(items, key=lambda v: items[v]["last"], reverse=True)


def _suggestions(known: list, history_items: list) -> list:
    used = set(history_items)
    cap = max(0, 10 - len(history_items))
    return [k for k in known if k not in used][:cap]


# ── Terminal UI helpers ───────────────────────────────────────────────────────


def _choose(label: str, options: list, current: str = "", history_items: list | None = None) -> str:
    history_items = history_items or []
    print(f"\n{label}")
    all_shown: list = []

    if history_items:
        print("  ── yours ──")
        for item in history_items:
            print(f"  {len(all_shown) + 1:2}. {item}")
            all_shown.append(item)
        if options:
            print("  ── suggestions ──")
            for item in options:
                print(f"  {len(all_shown) + 1:2}. {item}")
                all_shown.append(item)
    else:
        for item in options:
            print(f"  {len(all_shown) + 1:2}. {item}")
            all_shown.append(item)

    default = current or (history_items[0] if history_items else "")
    if all_shown:
        hint = f'keep "{default}"' if default else "skip"
        print(f"  → Enter a number, type your own, or press Enter to {hint}.")
    raw = input("  > ").strip()
    if not raw:
        return default
    if raw.isdigit() and all_shown:
        idx = int(raw) - 1
        if 0 <= idx < len(all_shown):
            return all_shown[idx]
    return raw


def _ask(label: str, current: str = "", hint: str = "") -> str:
    suffix = f" [{current}]" if current else (f" ({hint})" if hint else "")
    raw = input(f"\n{label}{suffix}: ").strip()
    return raw if raw else current


def _choose_multi(label: str, history_items: list, current: list | None = None, max_history: int = 0) -> list:
    """Toggleable checklist backed by history, with free-text additions."""
    if max_history:
        history_items = history_items[:max_history]
    in_history = set(history_items)
    extras = [i for i in (current or []) if i not in in_history]
    all_items: list = extras + list(history_items)
    checked: set = set(current or [])

    print(f"\n{label}")
    print("  Toggle by number, type a new entry, or press Enter when done.")
    while True:
        print()
        if all_items:
            for idx, item in enumerate(all_items, 1):
                mark = "x" if item in checked else " "
                print(f"  [{mark}] {idx:2}. {item}")
        else:
            print("  (no previous entries — type to add)")
        raw = input("\n  > ").strip()
        if not raw:
            break
        if raw.isdigit():
            i = int(raw) - 1
            if 0 <= i < len(all_items):
                item = all_items[i]
                if item in checked:
                    checked.discard(item)
                else:
                    checked.add(item)
        else:
            if raw in all_items:
                checked.add(raw)
            else:
                all_items.append(raw)
                checked.add(raw)
    return [item for item in all_items if item in checked]


# ── Roll YAML ─────────────────────────────────────────────────────────────────


def load_roll_yaml(folder: Path) -> dict:
    path = folder / "roll.yaml"
    if not path.exists():
        return {}
    result = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.split("#")[0].strip()
        if not line:
            continue
        key, sep, value = line.partition(":")
        if sep:
            result[key.strip().lower()] = value.strip().strip('"').strip("'")
    return result


def write_roll_yaml(folder: Path, data: dict, preserve_generated: bool = True) -> None:
    """Write roll.yaml from a data dict, optionally preserving the generated section."""
    path = folder / "roll.yaml"
    generated_section = ""
    if preserve_generated and path.exists():
        content = path.read_text(encoding="utf-8")
        idx = content.find(GENERATED_MARKER)
        if idx != -1:
            generated_section = "\n" + content[idx:]

    label = data.get("label", "")
    yaml_lines = (
        "# Roll manifest\n"
        f'film:       "{data.get("film", "")}"\n'
        f'camera:     "{data.get("camera", "")}"\n'
        f'lens:       "{data.get("lens", "")}"\n'
        f'date:       "{data.get("date", "")}"\n'
        f'location:   "{data.get("location", "")}"\n'
        f'subjects:   "{data.get("subjects", "")}"\n'
        f'lab:        "{data.get("lab", "")}"\n'
        f'lab_notes:  "{data.get("lab_notes", "")}"\n'
        f'notes:      "{data.get("notes", "")}"\n'
        + (f'label:      "{label}"\n' if label else "")
    )
    path.write_text(yaml_lines + generated_section, encoding="utf-8")


def run_roll_setup(folder: Path, prompt_process: bool = True) -> bool:
    path = folder / "roll.yaml"
    existing = load_roll_yaml(folder) if path.exists() else {}
    action = "Editing" if existing else "Setting up"
    print(f"\n{action} roll for: {folder}\n")

    history = _load_history()

    film_hist = _history_sorted(history, "film")
    film      = _choose("Film stock:", _suggestions(KNOWN_FILM_STOCKS, film_hist),
                        existing.get("film", ""), history_items=film_hist)

    cam_hist  = _history_sorted(history, "camera")
    camera    = _choose("Camera:", _suggestions(KNOWN_CAMERAS, cam_hist),
                        existing.get("camera", ""), history_items=cam_hist)

    lens_list = _choose_multi(
        "Lenses:",
        history_items=_history_sorted(history, "lens"),
        current=_split_list_field(existing.get("lens", "")),
    )
    lens = _join_list_field(lens_list)

    default_date = existing.get("date", "") or datetime.now().strftime("%Y-%m")
    date     = _ask("Date (YYYY-MM or YYYY-MM-DD)", existing.get("date", ""), default_date) or default_date

    loc_list = _choose_multi(
        "Locations:",
        history_items=_history_sorted(history, "location"),
        current=_split_list_field(existing.get("location", "")),
        max_history=10,
    )
    location = _join_list_field(loc_list)

    subj_list = _choose_multi(
        "Subjects (people, pets, or landmarks):",
        history_items=_history_sorted(history, "subjects"),
        current=_split_list_field(existing.get("subjects", "")),
        max_history=10,
    )
    subjects = _join_list_field(subj_list)

    lab_hist  = _history_sorted(history, "lab")
    if lab_hist:
        lab = _choose("Lab:", [], existing.get("lab", ""), history_items=lab_hist)
    else:
        lab = _ask("Lab", existing.get("lab", ""), "e.g. Mein Film Lab")

    lab_notes_hist = _history_sorted(history, "lab_notes")
    if lab_notes_hist:
        lab_notes = _choose("Lab instructions:", [], existing.get("lab_notes", ""), history_items=lab_notes_hist)
    else:
        lab_notes = _ask("Lab instructions", existing.get("lab_notes", ""), "e.g. push 1 stop")

    notes    = _ask("Notes", existing.get("notes", ""))
    label    = _ask("Label (optional)", existing.get("label", ""), "page title and folder suffix, e.g. Oslo Summer 2024")

    _record(history, "film",      film)
    _record(history, "camera",    camera)
    for _lens in lens_list:
        _record(history, "lens", _lens)
    for _loc in loc_list:
        _record(history, "location", _loc)
    for _subj in subj_list:
        _record(history, "subjects", _subj)
    _record(history, "lab",       lab)
    _record(history, "lab_notes", lab_notes)
    _save_history(history)

    write_roll_yaml(folder, {
        "film": film, "camera": camera, "lens": lens, "date": date,
        "location": location, "subjects": subjects, "lab": lab,
        "lab_notes": lab_notes, "notes": notes, "label": label,
    })

    print(f"\n✓  Saved: {path}")
    if not prompt_process:
        return True
    ans = input("\nStart processing now? [Y/n] ").strip().lower()
    if ans not in ("", "y", "yes"):
        print(f"   Run:   python3 contact.py {folder}\n")
        return False
    return True
